version: "3.9"

services:
  api:
    build: .
    container_name: pdf_api
    volumes:
      - ./data:/app/data   
      - ./logs:/app/logs 
    ports:
      - "8000:8000"
    restart: unless-stopped
